version: "3.9"
services:
  influxdb:
    image: "influxdb:2.6.1"
    user: 1000:1000
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin@intel
      - DOCKER_INFLUXDB_INIT_ORG=intel
      - DOCKER_INFLUXDB_INIT_BUCKET=intel
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=_hnEeqaA9pZmHZpU4sroPmm-9VstwJekiQjuXbCVWk5ZuJ18gUCllTEkfKLZUNkOLYGkm0lMbvtFO-M4MkWBmA==
      - DOCKER_INFLUXDB_INIT_RETENTION=8h
      - INFLUXD_TLS_KEY=/etc/ssl/self-signed.key
      - INFLUXD_TLS_CERT=/etc/ssl/self-signed.crt
    volumes:
      - config:/etc/influxdb2
      - data:/var/lib/influxdb2
      - /data/intelSSL/influxdb:/etc/ssl/
    ports:
      - "58100:8086"
volumes:
  config:
    external: false
  data:
    external: false
