receivers:

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  influxdb:
    endpoint: http://192.168.1.107:32701
    timeout: 500ms
    org: intel
    bucket: intel
    token: X6zYQsXQdkC4K-WE7Uza_Z7yYWkENe3PAbNPIjryr4_KECA75QoLqALgsX9XQjWMFhdhZFz1TiLjxYUiM7B1zw==
    metrics_schema: telegraf-prometheus-v1

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [influxdb]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [influxdb]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [influxdb]
