{
 "title": "Intel Cluster Node Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostlist",
    "label": "Host",
    "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\")\r\n  |> group()\r\n  |> distinct(column: \"host\")\r\n  "
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage System",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"cpu_usage_idle\" and r.cpu== \"cpu-total\"\r\n  )\r\n    |> filter(fn: (r) => contains(value: r[\"host\"], set: ${hostlist:json}))\r\n  |> map(fn: (r) => ({host:r.host,_value: 100.0 - r._value, _time: r._time, _start: r._start, _stop:r._stop }))\r\n //|> map(fn: (r) => ({r with _value: 100.0 - r._value}))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"cpu_usage_idle\" and r.cpu== \"cpu-total\"\r\n  )\r\n    |> filter(fn: (r) => contains(value: r[\"host\"], set: ${hostlist:json}))\r\n  |> map(fn: (r) => ({host:r.host,_value: 100.0 - r._value, _time: r._time, _start: r._start, _stop:r._stop }))\r\n //|> map(fn: (r) => ({r with _value: 100.0 - r._value}))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_used_percent\")  \r\n   |> filter(fn: (r) => contains(value: r[\"host\"], set: ${hostlist:json}))\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_used_percent\")  \r\n   |> filter(fn: (r) => contains(value: r[\"host\"], set: ${hostlist:json}))\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "i915 GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"gpu_busyness_3d_percentage_01_value\"\r\n  )"
    }
   ]
  },
  {
   "title": "i915 GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"gpu_busyness_3d_percentage_01_value\"\r\n  )"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n  |> filter(fn: (r) => contains(value: r[\"host\"], set: ${hostlist:json}))\r\n  |> map(fn: (r) => ({host:r.host,package_id:r.package_id,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n  |> filter(fn: (r) => contains(value: r[\"host\"], set: ${hostlist:json}))\r\n  |> map(fn: (r) => ({host:r.host,package_id:r.package_id,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "Utilization of each logical core",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket:\"intel\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> filter(fn: (r) => contains(value: r[\"host\"], set: ${hostlist:json}))\r\n          |> sort(columns: [\"host\"])\r\n          |> last()\r\n          |> map(fn: (r) => ({hostcpu: strings.joinStr(arr: [r.host,r.cpu ], v: \"-\"),_value: 100.00 - r._value, _time: r._time, _start: r._start, _stop:r._stop }))\r\n          |> group(columns: [\"hostcpu\"])\r\n          |> pivot(rowKey: [\"_time\"], columnKey: [\"hostcpu\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Network Packets Received",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"net_packets_recv\" and (r.interface == \"eno1\" or r.interface == \"enp3s0\")\r\n  )\r\n  |> filter(fn: (r) => contains(value: r[\"host\"], set: ${hostlist:json}))\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))\r\n"
    }
   ]
  },
  {
   "title": "Network Packets Sent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 11, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"net_packets_sent\" and r.interface == \"eno1\"\r\n  )\r\n  |> filter(fn: (r) => contains(value: r[\"host\"], set: ${hostlist:json}))\r\n  |> map(fn: (r) => ({host:r.host,_value: r._value, _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  }
 ]
}