{
 "title": "Home Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Living Air-cond Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tapo_p110_value\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Air Cond Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"tapo_p110_value\"\r\n  )"
    }
   ]
  },
  {
   "title": "Living Room Person Detection",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"jetson_cam01_value\"\r\n  )"
    }
   ]
  },
  {
   "title": "DPDK TGL01 Test",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"dpdk_tx_total_bytes\"\r\n  )"
    }
   ]
  },
  {
   "title": "Fluent-Bit Test",
   "type": "logs",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"intel\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"logs\"\r\n  )"
    }
   ]
  }
 ]
}