{
 "title": "Cluster Power Consumption Overview Copy",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "kWh_price", "label": "USD/kWh", "query": "0.174" },
   { "name": "co2factor", "label": " CO2/kWh Factor", "query": "0.21016" },
   { "name": "buckets", "label": "Buckets", "query": "buckets()" },
   {
    "name": "timeinterval",
    "label": "Resolution",
    "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> group()\r\n  |> elapsed(unit: 1s)\r\n  |>sum(column:\"elapsed\")\r\n  |> map(\r\n        fn: (r) => ({\r\n            elapse: r.elapsed,\r\n            duration: \r\n            if r.elapsed < 600.00 then \"30s\" \r\n            else if r.elapsed > 600.00 and r.elapsed < 3600.00 then \"1m\"\r\n            else if r.elapsed > 3600.00 and r.elapsed < 86400.00 then \"1h\"\r\n            else if r.elapsed > 86400.00 and r.elapsed < 259200.00 then \"3h\"\r\n            else if r.elapsed > 259200.00 and r.elapsed < 432000.00 then \"6h\"\r\n            else \"1d\",\r\n           }),\r\n    )\r\n  |>drop(columns:[\"elapse\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster nodes CPU overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket:\"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n  |> group(columns: [\"host\"])\r\n  |> distinct(column: \"host\")\r\n  |> count()\r\n  |> group()\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Total cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n  |> group(columns: [\"host\"])\r\n  |> distinct(column: \"cpu\")\r\n  |> count()\r\n  |> group()\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Cores without any workload (Idle)",
   "type": "stat",
   "description": "Cores that had utilization:\n- average < 2%\n- peak < 5%",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "t1 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> mean()\r\n          |> filter(fn: (r) => r[\"_value\"] > 98.00)\r\n\r\nt2 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> min()\r\n          |> filter(fn: (r) => r[\"_value\"] > 95.00)\r\n        \r\n\r\nunion(tables: [t1, t2])\r\n|> distinct(column: \"cpu\")\r\n|> group()\r\n|> count()"
    }
   ]
  },
  {
   "title": "Cores with workload (Running)",
   "type": "stat",
   "description": "Not classified as Idle nor Busy",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "t1 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])          \r\n          |> mean()\r\n          |> filter(fn: (r) => r[\"_value\"] <= 1)\r\n\r\nt2 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])          \r\n          |> min()\r\n          |> filter(fn: (r) => r[\"_value\"] == 0.00)\r\n        \r\n\r\nbusy = union(tables: [t1, t2])\r\n|> distinct(column: \"cpu\")\r\n|> group()\r\n|> count()\r\n\r\nt3 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> mean()\r\n          |> filter(fn: (r) => r[\"_value\"] > 98.00)\r\n\r\nt4 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> min()\r\n          |> filter(fn: (r) => r[\"_value\"] > 95.00)\r\n        \r\n\r\nidle = union(tables: [t3, t4])\r\n|> distinct(column: \"cpu\")\r\n|> group()\r\n|> count()\r\n\r\ntotal = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n  |> group(columns: [\"host\",\"cpu\"])    \r\n  |> distinct(column: \"cpu\")\r\n  |> group()\r\n  |> count()\r\n\r\nused = union(tables: [busy, idle])\r\n     |> sum()\r\n     |> map(fn: (r) => ({r with _value: r._value * -1}))\r\n\r\nunion(tables: [used, total])\r\n|>sum()\r\n"
    }
   ]
  },
  {
   "title": "Cores with heavy workload (Busy)",
   "type": "stat",
   "description": "Cores that had utilization:\n- average >= 99.00%\n- peak >= 99.99%",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "t1 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])          \r\n          |> mean()\r\n          |> filter(fn: (r) => r[\"_value\"] <= 1)\r\n\r\nt2 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])          \r\n          |> min()\r\n          |> filter(fn: (r) => r[\"_value\"] == 0.00)\r\n        \r\n\r\nunion(tables: [t1, t2])\r\n|> distinct(column: \"cpu\")\r\n|> group()\r\n|> count()"
    }
   ]
  },
  {
   "title": "Cluster nodes power breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster nodes CPU / DRAM ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nt1 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])          \r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value <= 1 then r.host else \"null\",\r\n           cpu: if r._value <= 1 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt2 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])          \r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value == 0.00 then r.host else \"null\",\r\n           cpu: if r._value == 0.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nbusyhost = union(tables: [t1, t2])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nbusycpu = union(tables: [t1, t2])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n busyhostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n   |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: busyhost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: busycpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: busyhost) and contains(value: r.cpu_id, set: busycpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n\r\n  from(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: busyhost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: busyhostwithpckid)) \r\n |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n\r\n "
    },
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_dram_power_consumption_watts\")\r\n |> group()\r\n |> aggregateWindow(every: ${timeinterval}, fn: sum)"
    },
    {
     "query": "import \"strings\"\r\n\r\nt3 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 98.00 then r.host else \"null\",\r\n           cpu: if r._value > 98.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt4 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 95.00 then r.host else \"null\",\r\n           cpu: if r._value > 95.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nidlehost = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlecpu = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlehostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: idlehost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: idlecpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: idlehost) and contains(value: r.cpu_id, set: idlecpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )\r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n\r\nfrom(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\") \r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: idlehost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: idlehostwithpckid))\r\n |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n \r\n"
    },
    {
     "query": "import \"strings\"\r\n\r\nt1 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])          \r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value <= 1 then r.host else \"null\",\r\n           cpu: if r._value <= 1 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt2 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])          \r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value == 0.00 then r.host else \"null\",\r\n           cpu: if r._value == 0.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nbusyhost = union(tables: [t1, t2])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nbusycpu = union(tables: [t1, t2])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n busyhostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n   |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: busyhost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: busycpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: busyhost) and contains(value: r.cpu_id, set: busycpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nbusypower = from(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: busyhost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: busyhostwithpckid))\r\n\r\n\r\nt3 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 98.00 then r.host else \"null\",\r\n           cpu: if r._value > 98.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt4 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 95.00 then r.host else \"null\",\r\n           cpu: if r._value > 95.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nidlehost = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlecpu = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlehostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: idlehost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: idlecpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: idlehost) and contains(value: r.cpu_id, set: idlecpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )\r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlepower = from(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\") \r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: idlehost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: idlehostwithpckid))\r\n \r\n\r\n \r\nusedcpu = union(tables: [idlepower, busypower])\r\n|> map(fn: (r) => ({ hostcpu: strings.joinStr(arr: [r.host,r.package_id ], v: \", \"), _value:r._value }))\r\n|> group()\r\n|> distinct(column: \"hostcpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n\r\nfrom(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n |> group()\r\n |> map(fn: (r) => ({ hostcpu: strings.joinStr(arr: [r.host,r.package_id ], v: \", \"), _value:r._value ,\r\n _time: r._time, _start: r._start, _stop:r._stop }))\r\n |> filter(fn: (r) => not contains(value: r.hostcpu, set: usedcpu)) \r\n |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n"
    }
   ]
  },
  {
   "title": "Cluster nodes CPU-only power consumption (now)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n  |> group()\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)"
    }
   ]
  },
  {
   "title": "Cluster nodes CPU savings opportunity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster nodes CPU power savings opportunity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n |> group()\r\n |> aggregateWindow(every: ${timeinterval}, fn: sum)"
    },
    {
     "query": "import \"strings\"\r\n\r\nimport \"strings\"\r\n\r\nt3 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 98.00 then r.host else \"null\",\r\n           cpu: if r._value > 98.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt4 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 95.00 then r.host else \"null\",\r\n           cpu: if r._value > 95.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nidlehost = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlecpu = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlehostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: idlehost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: idlecpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: idlehost) and contains(value: r.cpu_id, set: idlecpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )\r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n\r\nfrom(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\") \r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: idlehost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: idlehostwithpckid))\r\n |> map(fn: (r) => ({host:r.host,package_id: r.package_id, _value: r._value * 0.25, _time: r._time, _start: r._start, _stop:r._stop }))\r\n |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n\r\n"
    }
   ]
  },
  {
   "title": "Estimated savings from putting idle cores to C6",
   "type": "stat",
   "description": "*Estimated savings from putting idle cores to C6*\n\nCore is considered idle when average busy cycles percentage is < 2% and peak < 5%\n\nPower can be saved when:\n- Core is in running state despite low load\n- Core is in C1 state but could be in C6",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nimport \"strings\"\r\n\r\nt3 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 98.00 then r.host else \"null\",\r\n           cpu: if r._value > 98.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt4 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 95.00 then r.host else \"null\",\r\n           cpu: if r._value > 95.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nidlehost = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlecpu = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlehostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: idlehost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: idlecpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: idlehost) and contains(value: r.cpu_id, set: idlecpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )\r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n\r\nfrom(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\") \r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: idlehost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: idlehostwithpckid))\r\n |> map(fn: (r) => ({host:r.host,package_id: r.package_id, _value: r._value * 0.25, _time: r._time, _start: r._start, _stop:r._stop }))\r\n |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n\r\n"
    }
   ]
  },
  {
   "title": "Estimated energy savings from putting cores to C6 (last 24h)",
   "type": "stat",
   "description": "*Estimated energy savings from putting cores to C6 (last 24h)*",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nimport \"strings\"\r\n\r\nt3 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 98.00 then r.host else \"null\",\r\n           cpu: if r._value > 98.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt4 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 95.00 then r.host else \"null\",\r\n           cpu: if r._value > 95.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nidlehost = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlecpu = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlehostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: idlehost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: idlecpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: idlehost) and contains(value: r.cpu_id, set: idlecpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )\r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n\r\nfrom(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\") \r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: idlehost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: idlehostwithpckid))\r\n |> map(fn: (r) => ({host:r.host,package_id: r.package_id, _value: r._value * 0.25, _time: r._time, _start: r._start, _stop:r._stop }))\r\n |> aggregateWindow(every: 1h, fn: sum)\r\n |> group()\r\n |> map(fn: (r) => ({_value: (r._value / 1000.00) * 24.00 , _time: r._time, _start: r._start, _stop:r._stop }))\r\n\r\n"
    }
   ]
  },
  {
   "title": "Estimated annual energy savings from putting cores to C6",
   "type": "stat",
   "description": "*Estimated annual energy savings from putting cores to C6*",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nt3 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 98.00 then r.host else \"null\",\r\n           cpu: if r._value > 98.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt4 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 95.00 then r.host else \"null\",\r\n           cpu: if r._value > 95.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nidlehost = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlecpu = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlehostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: idlehost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: idlecpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: idlehost) and contains(value: r.cpu_id, set: idlecpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )\r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n\r\nfrom(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\") \r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: idlehost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: idlehostwithpckid))\r\n |> map(fn: (r) => ({host:r.host,package_id: r.package_id, _value: r._value * 0.25, _time: r._time, _start: r._start, _stop:r._stop }))\r\n |> aggregateWindow(every: 1h, fn: sum)\r\n |> group()\r\n |> map(fn: (r) => ({_value: (r._value / 1000.00) * 24.00 * 365.00 , _time: r._time, _start: r._start, _stop:r._stop }))\r\n  \r\n\r\n"
    }
   ]
  },
  {
   "title": "Environmental and financial cost of CPUs energy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "kWh consumed in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n  |> group()\r\n  |> aggregateWindow(every: 1h, fn: sum)\r\n  |> map(fn: (r) => ({_value: (r._value / 1000.00) * 24.00 , _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "Energy cost of the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n  |> group()\r\n  |> aggregateWindow(every: 1h, fn: sum)\r\n  |> map(fn: (r) => ({_value: ((r._value / 1000.00) * 24.00) * ${kWh_price} , _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "Estimated cost savings from putting cores to C6 (last 24h)",
   "type": "stat",
   "description": "Pounds/kWh factor from UK government statistical-data-sets, \"Annual domestic energy price statistics\" for 2020",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nt3 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 98.00 then r.host else \"null\",\r\n           cpu: if r._value > 98.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt4 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 95.00 then r.host else \"null\",\r\n           cpu: if r._value > 95.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nidlehost = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlecpu = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlehostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: idlehost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: idlecpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: idlehost) and contains(value: r.cpu_id, set: idlecpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )\r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n\r\nfrom(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\") \r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: idlehost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: idlehostwithpckid))\r\n |> map(fn: (r) => ({host:r.host,package_id: r.package_id, _value: r._value * 0.25, _time: r._time, _start: r._start, _stop:r._stop }))\r\n |> aggregateWindow(every: 1h, fn: sum)\r\n |> group()\r\n |> map(fn: (r) => ({_value: ((r._value / 1000.00) * 24.00) * ${kWh_price} , _time: r._time, _start: r._start, _stop:r._stop }))\r\n\r\n"
    }
   ]
  },
  {
   "title": "Estimated CO2 emissions (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n  |> group()\r\n  |> aggregateWindow(every: 1h, fn: sum)\r\n  |> map(fn: (r) => ({_value: ((r._value / 1000.00) * 24.00) * ${co2factor} , _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "Estimated CO2 emissions savings from putting cores to C6 (last 24h)",
   "type": "stat",
   "description": "*Estimated CO2 emissions savings from putting cores to C6 (last 24h)*\n\nCO2/kWh factor from UK government webpage, \"Greenhouse gas reporting: conversion factors 2021\"",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nt3 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 98.00 then r.host else \"null\",\r\n           cpu: if r._value > 98.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt4 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 95.00 then r.host else \"null\",\r\n           cpu: if r._value > 95.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nidlehost = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlecpu = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlehostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: idlehost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: idlecpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: idlehost) and contains(value: r.cpu_id, set: idlecpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )\r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n\r\nfrom(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\") \r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: idlehost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: idlehostwithpckid))\r\n |> map(fn: (r) => ({host:r.host,package_id: r.package_id, _value: r._value * 0.25, _time: r._time, _start: r._start, _stop:r._stop }))\r\n |> aggregateWindow(every: 1h, fn: sum)\r\n |> group()\r\n |> map(fn: (r) => ({_value: ((r._value / 1000.00) * 24.00) * ${co2factor} , _time: r._time, _start: r._start, _stop:r._stop }))\r\n\r\n"
    }
   ]
  },
  {
   "title": "Estimated annual energy consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n  |> group()\r\n  |> aggregateWindow(every: 1h, fn: sum)\r\n  |> map(fn: (r) => ({_value: ((r._value / 1000.00) * 24.00) * 365.00 , _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "Estimated annual energy cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n  |> group()\r\n  |> aggregateWindow(every: 1h, fn: sum)\r\n  |> map(fn: (r) => ({_value: (((r._value / 1000.00) * 24.00) * 365.00) * ${kWh_price} , _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "Estimated annual cost savings from putting cores to C6",
   "type": "stat",
   "description": "Pounds/kWh factor from UK government statistical-data-sets, \"Annual domestic energy price statistics\" for 2020",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nt3 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 98.00 then r.host else \"null\",\r\n           cpu: if r._value > 98.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt4 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 95.00 then r.host else \"null\",\r\n           cpu: if r._value > 95.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nidlehost = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlecpu = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlehostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: idlehost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: idlecpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: idlehost) and contains(value: r.cpu_id, set: idlecpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )\r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n\r\nfrom(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\") \r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: idlehost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: idlehostwithpckid))\r\n |> map(fn: (r) => ({host:r.host,package_id: r.package_id, _value: r._value * 0.25, _time: r._time, _start: r._start, _stop:r._stop }))\r\n |> aggregateWindow(every: 1h, fn: sum)\r\n |> group()\r\n |> map(fn: (r) => ({_value: ((r._value / 1000.00) * 24.00 * 365.00) * ${kWh_price} , _time: r._time, _start: r._start, _stop:r._stop }))\r\n\r\n"
    }
   ]
  },
  {
   "title": "Estimated annual CO2 emissions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\")\r\n  |> group()\r\n  |> aggregateWindow(every: 1h, fn: sum)\r\n  |> map(fn: (r) => ({_value: (((r._value / 1000.00) * 24.00) * 365.00) * ${co2factor} , _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "Estimated annual CO2 emissions savings from putting cores to C6",
   "type": "stat",
   "description": "*Estimated annual CO2 emissions savings from putting cores to C6*\n\nCO2/kWh factor from UK government webpage, \"Greenhouse gas reporting: conversion factors 2021\"",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nt3 =\r\n    from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: mean)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 98.00 then r.host else \"null\",\r\n           cpu: if r._value > 98.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n\r\nt4 =\r\n     from(bucket:\"${buckets}\")\r\n          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_usage_idle\" and r.cpu != \"cpu-total\")\r\n          |> group(columns: [\"host\",\"cpu\"])\r\n          |> aggregateWindow(every: ${timeinterval}, fn: min)\r\n          |> map(\r\n        fn: (r) => ({\r\n           host: if r._value > 95.00 then r.host else \"null\",\r\n           cpu: if r._value > 95.00 then r.cpu else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )  \r\n    |> group(columns: [\"host\",\"cpu\"])\r\n        \r\n\r\nidlehost = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"host\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlecpu = union(tables: [t3, t4])\r\n |> map(fn: (r) => ({r with cpu: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)}))\r\n |> group()\r\n |> distinct(column: \"cpu\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\nidlehostwithpckid = from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_core_cpu_frequency_mhz\")\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n  |> map(\r\n        fn: (r) => ({\r\n           host: if contains(value: r.host, set: idlehost) then r.host else \"null\",\r\n           cpu_id: if contains(value: r.cpu_id, set: idlecpu) then r.cpu_id else \"null\",\r\n           package_id: if contains(value: r.host, set: idlehost) and contains(value: r.cpu_id, set: idlecpu) then r.package_id else \"null\",\r\n           core_id: if exists r.core_id then r.core_id else \"null\",\r\n           _value: if exists r._value then r._value else 0.00,\r\n           _time: if exists r._time then r._time else now(),\r\n           _start: if exists r._start then r._start else now(),\r\n           _stop: if exists r._stop then r._stop else now(),\r\n           }),\r\n    )\r\n |> group()\r\n |> distinct(column: \"package_id\")\r\n |> tableFind(fn: (key) => true)\r\n |> getColumn(column: \"_value\")\r\n\r\n\r\nfrom(bucket: \"${buckets}\")\r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_power_consumption_watts\") \r\n |> group()\r\n |> filter(fn: (r) => contains(value: r.host, set: idlehost))\r\n |> filter(fn: (r) => contains(value: r.package_id, set: idlehostwithpckid))\r\n |> map(fn: (r) => ({host:r.host,package_id: r.package_id, _value: r._value * 0.25, _time: r._time, _start: r._start, _stop:r._stop }))\r\n |> aggregateWindow(every: 1h, fn: sum)\r\n |> group()\r\n |> map(fn: (r) => ({_value: ((r._value / 1000.00) * 24.00 * 365.00) * ${co2factor} , _time: r._time, _start: r._start, _stop:r._stop }))\r\n\r\n"
    }
   ]
  },
  {
   "title": "Cluster nodes memory savings opportunity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used memory %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_used\" or r[\"_measurement\"] == \"mem_total\")\r\n  |> sort(columns: [\"_time\"])\r\n  |>toFloat()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({host:r.host, _value:(r.mem_used / r.mem_total) * 100.00, _time: r._time, _start: r._start, _stop:r._stop }))\r\n  |>group()\r\n  |> aggregateWindow(every: ${timeinterval}, fn: max)\r\n"
    }
   ]
  },
  {
   "title": "Memory not used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_available\")\r\n  |> group()\r\n  |> aggregateWindow(every: 1h, fn: sum)"
    }
   ]
  },
  {
   "title": "Energy consumed by redundant memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_dram_power_consumption_watts\" or r[\"_measurement\"] == \"mem_available_percent\")\r\n  |>drop(columns: [\"package_id\"])\r\n  |> sort(columns: [\"_time\"])\r\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n|>group()\r\n|> map(fn: (r) => ({host:r.host, _value:(r.powerstat_package_current_dram_power_consumption_watts * (r.mem_available_percent / 100.00)) * ${kWh_price} , _time: r._time, _start: r._start, _stop:r._stop }))\r\n|> aggregateWindow(every: 1h, fn: sum)\r\n|> map(fn: (r) => ({host:r.host, _value:(r._value / 1000.00), _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "Used memory total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem_used\")\r\n  |> group()\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n"
    }
   ]
  },
  {
   "title": "Money spent on excess electricity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_dram_power_consumption_watts\" or r[\"_measurement\"] == \"mem_available_percent\")\r\n  |>drop(columns: [\"package_id\"])\r\n  |> sort(columns: [\"_time\"])\r\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n|>group()\r\n|> map(fn: (r) => ({host:r.host, _value:(r.powerstat_package_current_dram_power_consumption_watts * (r.mem_available_percent / 100.00)) * ${kWh_price} , _time: r._time, _start: r._start, _stop:r._stop }))\r\n|> aggregateWindow(every: 1h, fn: sum)\r\n|> map(fn: (r) => ({host:r.host, _value:(r._value / 1000.00) * ${kWh_price}, _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "CO2 emitted by excess electricity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_dram_power_consumption_watts\" or r[\"_measurement\"] == \"mem_available_percent\")\r\n  |>drop(columns: [\"package_id\"])\r\n  |> sort(columns: [\"_time\"])\r\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n|>group()\r\n|> map(fn: (r) => ({host:r.host, _value:(r.powerstat_package_current_dram_power_consumption_watts * (r.mem_available_percent / 100.00)) * ${kWh_price} , _time: r._time, _start: r._start, _stop:r._stop }))\r\n|> aggregateWindow(every: 1h, fn: sum)\r\n|> map(fn: (r) => ({host:r.host, _value:(r._value / 1000.00) * ${co2factor}, _time: r._time, _start: r._start, _stop:r._stop }))"
    }
   ]
  },
  {
   "title": "Watts used on memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerstat_package_current_dram_power_consumption_watts\")\r\n  |>group()\r\n  |> aggregateWindow(every: ${timeinterval}, fn: sum)\r\n"
    }
   ]
  }
 ]
}