receivers:
  otlp:
    protocols:
      grpc:
      http:
        tls:
          cert_file: /etc/ssl/self-signed.crt
          key_file: /etc/ssl/self-signed.key

processors:
  batch:

exporters:
  otlp:
    endpoint: https://192.168.1.22:52123
    tls:
      insecure: false
      #ca_file: /etc/ssl/loadbalancerserver/self-signed.crt
      cert_file: /etc/ssl/self-signed.crt
      key_file: /etc/ssl/self-signed.key
      min_version: "1.1"
      max_version: "1.2"
      insecure_skip_verify: true

service:

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
      #exporters: [influxdb]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
      #exporters: [influxdb]


